{% set name = "yaqd-rgb" %}
{% set version = "2021.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaqd-rgb-{{ version }}.tar.gz
  sha256: 1d8b0ec11c13f54e16ab651dc2922da5a866ff5334627ce7b4e055f802c26ac5

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-rgb-qmini = yaqd_rgb._rgb_qmini:RGBQmini.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit
  run:
    - python >=3.7
    - flit
    - pyusb
    - numpy
    - yaqd-core >=2020.06.3

test:
  imports:
    - yaqd_rgb
    - yaqd_rgb.rgbdriverkit
  commands:
    - pip check
    - yaqd-rgb-qmini --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for RGB Photonics hardware
  dev_url: https://gitlab.com/yaq/yaqd-rgb
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - LICENSE_RGBDRIVERKIT

extra:
  recipe-maintainers:
    - untzag
    - ksunden
    - kameyer226
    - ddkohler
